### ISSUE TITLE
Could not connect to the server

### ISSUE THREAD

**Issue by tnemrap** [molobrakos/volvooncall#10]
Get Could not connect to the server when using voc.

/Mike

**Comment by molobrakos** [comment]
Sorry, you need to provide better information than that to help out finding the cause for this problem when filing an issue.
1. Are you using the `voc` tool or the library (`volvooncall.py`)?
2. What is your configuration (any custom service url or region?)
3. Did you turn on increased logging? (`-vv`)
4. Any error messages?
5. Are you sure it was not a temporary network connection problem or server error?
6. Does it still not work?

**Comment by nikagl** [comment]
Agree. No problems here, working perfectly :)

**Comment by tnemrap** [comment]
Sorry
It is Volvo that have problem with their servers.
Have the same problem with app and web.
Called support and it will work soon.
