### ISSUE TITLE
Start Car

### ISSUE THREAD

**Issue by tnemrap** [molobrakos/volvooncall#14]
I can start my Car with the app, is this possible with VOC?

**Comment by molobrakos** [comment]
Not at the moment, but it is probably doable. A pull request for this is welcome! :-)

**Comment by molobrakos** [comment]
For this we have to find the commands to send ('engine/start' maybe?). Are you able to find out?

**Comment by tnemrap** [comment]
Trying to look for it.

**Comment by tnemrap** [comment]
Used Charles and it is engine/start and engine/stop.

**Comment by molobrakos** [comment]
Have you tried invoking `voc call engine/start`?

**Comment by tnemrap** [comment]
22:56:43 volvooncall: Request for https://vocapi.wirelesscar.net/customerapi/rest/v3.0/vehicles/YV1BW738DXXXXXXXX/engine/start
22:56:43 requests.packages.urllib3.connectionpool: https://vocapi.wirelesscar.net:443 "POST /customerapi/rest/v3.0/vehicles/YV1BW738DXXXXXXXX/engine/start HTTP/1.1" 500 98
22:56:43 volvooncall: Failure when communcating with the server: 500 Server Error: Internal Server Error for url: https://vocapi.wirelesscar.net/customerapi/rest/v3.0/vehicles/YV1BW738DXXXXXXXX/engine/start
22:56:43 volvooncall: Failure to execute: 500 Server Error: Internal Server Error for url: https://vocapi.wirelesscar.net/customerapi/rest/v3.0/vehicles/YV1BW738DXXXXXXXX/engine/start

When using app and charles it uses url https://vocapi.wirelesscar.net/customerapi/rest/vehicles/YV1BW738DXXXXXXXX/engine/start

**Comment by tnemrap** [comment]
Now i found that it needs data in POST statement.
The data is {"runtime":X} where X is 1 to 15 and is the minutes the engine should run.

**Comment by tnemrap** [comment]
I can start the car with this.
curl -H 'X-Client-Version: 4.1.5.21045' -H 'X-Device-Id: b3cbba373be4c28f' -H 'X-OS-Type: Android' -H 'X-OS-Version: 21' -H 'X-Originator-Type: app' -H 'Accept: application/vnd.wirelesscar.com.voc.Service.v4+json; charset=utf-8' -H 'X-Request-Id: 5eea940c-2b6b-40ea-9575-2dcfb78044ba' -H 'Locale: en_US' -H 'Authorization: Basic mysecret' -H 'Content-Type: application/vnd.wirelesscar.com.voc.EngineRemoteStart.v4+json; charset=utf-8' -H 'User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.0.1; GT-I9505 Build/LRX22C)' -H 'Host: vocapi.wirelesscar.net' --data-binary '{"runtime":5}' --compressed 'https://vocapi.wirelesscar.net/customerapi/rest/vehicles/YV1BW738DXXXXXXXX/engine/start'

**Comment by molobrakos** [comment]
Maybe now:?https://github.com/molobrakos/volvooncall/commit/719289f7890d3828315947a5b04588190e6485f1

**Comment by tnemrap** [comment]
Close but not yet:

Traceback (most recent call last):
  File "/usr/local/bin/voc", line 192, in <module>
    main()
  File "/usr/local/bin/voc", line 177, in main
    vehicle.start_engine()
  File "/usr/local/lib/python3.5/dist-packages/volvooncall.py", line 282,
in start_engine
    if self.engine_stop_supported:
AttributeError: 'Vehicle' object has no attribute 'engine_stop_supported'


2018-03-23 20:02 GMT+01:00 Erik Eriksson <notifications@github.com>:

**Comment by molobrakos** [comment]
D'oh!
https://github.com/molobrakos/volvooncall/commit/3a42fff5adb12ddeb2a9a4cda420167e9dcbcfe8

**Comment by molobrakos** [comment]
Does it work now? I haven't been able to test myself, since the car is parked in a garage a bit away from my house.

**Comment by molobrakos** [comment]
Closing for now, please re-open if still an issue.

**Comment by jorgesousa1975** [comment]
Why am I getting the error that can't connect to the host? that vocapi.wirelesscar.net:443 ssl:default [Name does not resolve]
