### ISSUE TITLE
timezone support possible for trips?

### ISSUE THREAD

**Issue by wivaku** [molobrakos/volvooncall#21]
The JSON for  timestamps is UTC (without timezone).
E.g.  
`"startTime": "2018-07-16T14:52:26+00:00",` (14:52 UTC)
instead of (in my case)  
`"startTime": "2018-07-16T16:52:26+02:00"` (16:52 CEST)

Does the API return timestamps with timezone? If so, can it be included in the output?

**Comment by molobrakos** [comment]
I am not sure what you are asking for. Do you mean that the server returns timestamps in some other timezone than UTC for you? For me timezone seems to be returned from the server: `tzinfo=datetime.timezone.utc`. Is that the case for you as well (add `-vv` to voc command line to see it). Do you want it to always be converted to the local timezone?

**Comment by wivaku** [comment]
The -vv data indeed shows UTC timezone:
`'startTime': datetime.datetime(2018, 7, 16, 14, 52, 26, tzinfo=datetime.timezone.utc)`
and `voc` returns it as UTC as well: `"startTime": "2018-07-16T14:52:26+00:00"`.

Indeed, I would like to get it in local timezone (or get the timezone offset): 16:52:26, which is local CEST time.
The Volvo On Call app shows it in local time (16:52), so I have the feeling this determined from some data in the API.

I can hardcode that for my home location (or use geonames lookup based on lat+lon), but that is not ideal.

**Comment by molobrakos** [comment]
I guess we could just default to display times in the local time zone (the time zone of the user, not the vehicle :-) and then have an option (`--utc`) to always display timestamps in UTC (+00:00).

**Comment by wivaku** [comment]
That would be nice. I wonder what will happen (in the regular Volvo On Call app) when I cross timezones. Will know next month.

**Comment by molobrakos** [comment]
https://github.com/molobrakos/volvooncall/commit/0e9591253ff028e12055357ff12c4fbfe7e48d75

**Comment by wivaku** [comment]
thx!
