### ISSUE TITLE
0.6.4 - Dashboard output defaulting to Scandinavian Miles mode without specifying option

### ISSUE THREAD

**Issue by mjpcomp** [molobrakos/volvooncall#27]
Unsure if this is due to the issue with the trips display, but, the dashboard now outputs in Scandinavian_Miles mode (mil and L/mil), rather than in km and L/100 km.

**Comment by molobrakos** [comment]
https://github.com/molobrakos/volvooncall/commit/7c58201e07bedaa6e743161d902a961ba437be84
