### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by tnemrap** [molobrakos/volvooncall#30]
How do i use the owntracks and mqtt function?

**Comment by molobrakos** [comment]
I noticed the owntracks option didn't quite work, fixed it here: https://github.com/molobrakos/volvooncall/commit/431746e2b8a0c6fb6a70d7ecbaa00381d6b757f0#diff-1b5fc1c8c4ef246585f7f1dff06e6bf0

For owntracks, just run as `voc owntracks` and pipe the result yourself into a command that publishes the result to a server and a topic of your choice (like `mosquitto_pub`). You need to run this command periodically, e.g. from a cron job.

The mqtt function is currently designed to integrate primarilty into Home Assistant. Your mqtt credentials needs to be configured in `$HOME/.config/mosquitto_pub` and by running `voc mqtt`, your vehicle status will periodically be published on the configured MQTT server.
