### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Timdebruijn** [molobrakos/volvooncall#31]
I got this Syntax error:

/opt/volvooncall$ ./voc
  File "./voc", line 226
    print(f'{instrument}: {instrument.str_state}')
                                                ^
SyntaxError: invalid syntax

**Comment by molobrakos** [comment]
What Python version are you using? Try using a version >= 3.6.

**Comment by molobrakos** [comment]
Closing for now, please reopen if this does not fix your problem.
