### ISSUE TITLE
'voc print remoteHeaterSupported' return "False" when heater is on

### ISSUE THREAD

**Issue by anglaborg** [molobrakos/volvooncall#35]
Hi,

Having trouble with `$ voc print remoteHeaterSupported` that returns `False` even though my heater is on. 
The heater starts in the car when I do `voc heater start`. 
`voc status` displays `Heater: on`

voc print heater do not give me a True or False return. 
 
Its a V60 2019 with diesel heater if that make sense.

**Comment by molobrakos** [comment]
try `voc print preclimatizationSupported`

**Comment by anglaborg** [comment]
@molobrakos 
`voc print preclimatizationSupported` gives me "True" in return even though my heater is off.

**Comment by molobrakos** [comment]
I am not sure I understand what the issue here is. The attributes `remoteHeaterSupported` and `preclimatizationSupported` only tells you if your car supports turning on/off heater/preclimatization, not if it is currently on or off.

**Comment by anglaborg** [comment]
I want to check if the heater is running or not. Like I could check if the engine is running.

**Comment by molobrakos** [comment]
Doesn't any of:
`voc status`
`voc status | grep -i heater`
`vos dashboard`
`vos dashboard | grep -i heater`
`voc print | jq .heater` (assuming you have the jq tool installed)
give you that information?

**Comment by anglaborg** [comment]
Yes, they are working correctly but im looking for a command that gives me `True` or `False` in return. Is there a command for that?
