### ISSUE TITLE
Request: add command line option for sending commands

### ISSUE THREAD

**Issue by nikagl** [molobrakos/volvooncall#4]
I have tried getting command line options to work, but just failed due the lack of my python knowledge. Can you add a command line option to customize the command sent?

The "preclimatization/start" post query, should be a variable that is parsed from command line option 3.

The response of the query (like "Status" = "Started") are added to the results. A post however also returns a response with the new service URL which can be used to see whether the message is delivered to the car (Status = MessageDelivered) and whether it was successfull (Status = Successfull). 

That could be added too to the script, but as I hate that it takes so long in the app anyway, I don't really mind not doing it :) ...

**Comment by tnemrap** [comment]
I am also interested of this to start heater and Lock the car.
I am doing this now with bash and curl.

/Mike

**Comment by nikagl** [comment]
@molobrakos needs to add it to his repo, but is still designing the basics. When you use my repo (https://github.com/nikagl/volvooncall) you can use it too (but need to manually change to the right request that you want to make),,, Find the line with "preclimatization/start" and replace with whatever you want (note: depending on the make of your car it might also be heater/start)...

**Comment by molobrakos** [comment]
Sorry, I'll merge this feature after new year's. Is there any way to determine if `preclimatization/start` or `heater/start` should be used?

**Comment by nikagl** [comment]
I figured it out by using a proxy because the heater/start generated an error. Looking at the log, the results are:

`u'remoteHeaterSupported': False`
and
`u'preclimatizationSupported': True`

So you could use the "Supported" items to see what is supported? Here's all of them returned from my car:
`u'assistanceCallSupported': Trueu'carLocatorSupported': True
u'climatizationCalendarVersionsSupported': []
u'engineStartSupported': False
u'highVoltageBatterySupported': True
u'honkAndBlinkSupported': True
u'honkAndBlinkVersionsSupported': [u'honkAndOrBlink' u'honkAndBlink']
u'journalLogSupported': True
u'lockSupported': True
u'overrideDelayChargingSupported': True
u'preclimatizationSupported': True
u'remoteHeaterSupported': False
u'sendPOIToVehicleVersionsSupported': [u'sendSinglePOIToVehicle']
u'status.parkedIndoor.supported': True
u'unlockSupported': True`

Regards,

Nika.

**Comment by tnemrap** [comment]
I use /heater/start and HTTP POST for /lock with data '{}'
/mike

**Comment by molobrakos** [comment]
I think this is supported now. Thanks for helping out! Please report test results if any problems.

**Comment by nikagl** [comment]
Yes, it works, although I had to install docopt (pip install docopt) and needed to rename voc to voc.py (on Windows with Python 2.7 btw)...

Regards,

Nika.
