### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by ewatech** [molobrakos/volvooncall#45]
Hi, I’m quite new with this.

This is all I get when I try to connect

19-01-26 09:09.20 WARNING (MainThread) [volvooncall.volvooncall] Failure when communcating with the server: 401, message='Unauthorized'

**Comment by molobrakos** [comment]
You can provide username and password using `-p`, and `-u` or in a configuration file. Apparently the server failed to authorize you so either you missed to provide valid credentials.
