### ISSUE TITLE
Vehicle not found

### ISSUE THREAD

**Issue by aoliu95** [molobrakos/volvooncall#47]
I put the .conf file into my Home on Mac, but it seems that VOC cannot find the vehicle when I ran any of the voc commends.
![xnip2019-02-02_23-59-56](https://user-images.githubusercontent.com/30453289/52174302-acb13780-2746-11e9-9406-7d720f0c6bef.jpg)

**Comment by molobrakos** [comment]
Try adding `-vv `for more verbose output: `voc -vv status`

**Comment by StephenPAdams** [comment]
@molobrakos I'm getting this same message. Using the verbose output, I'm seeing the accountVehicleRelations array is empty.

**Comment by molobrakos** [comment]
In that case I guess it is outside of our control ... does the app work, i.e. is there a vehicle associated with your account?

**Comment by StephenPAdams** [comment]
@molobrakos the app does work and I do have a vehicle associated to my account.

**Comment by molobrakos** [comment]
Does setting/changing the region help? (`-r`)

**Comment by StephenPAdams** [comment]
@molobrakos that looks to have done the trick, Erik. Thank you!

For those curious, I've set the region to na for North America and I've been able to successfully get my vehicle back. Just tried running multiple commands (remote starting and stopping) without issue.

**Comment by aoliu95** [comment]
> @molobrakos that looks to have done the trick, Erik. Thank you!
> 
> For those curious, I've set the region to na for North America and I've been able to successfully get my vehicle back. Just tried running multiple commands (remote starting and stopping) without issue.

Thanks, Stephen. Setting the region to na works for me also.
