### ISSUE TITLE
MQTT configuration + request for DockerHub repo

### ISSUE THREAD

**Issue by tger977** [molobrakos/volvooncall#68]
I'd like to use volvooncall and MQTT publishing to my MQTT broker. I have set up a Docker container but it looks like that a mqtt config file is missing. Could anybody help me out to find out:
1) where to put this config file?
2) an example of how this config file should look like? 
In this repo I do not find any information about mqtt requirements

Even better would be if a complete Docker repo would be published on DockerHub. This would make it much easier for people to use volooncall.

Thanks in advance!

**Comment by FireWizard52** [comment]
Hi,

Sorry to answer this question quite late, but I do not very often visit this github place anymore, as it looks that this project is more or less dead. Issues are not answered by the creator of this Python script and pull requests are not reviewed.

> I'd like to use volvooncall and MQTT publishing to my MQTT broker. I have set up a Docker container but it looks like that a mqtt config file is missing. Could anybody help me out to find out:

It is not actually a MQTT config file. It is part of the ,voc.conf file

> where to put this config file?

This .voc.conf is a hidden file and you have to place it in your home directory.

> an example of how this config file should look like?

If you need to communicate with a MQTT server, not installed on the same device as where the script runs, the config should be:

mqtt_url: mqtt://Username:Password@<IP Address>:1883
username: <Login name for your Volvo on Call app>
password: <Password used to login in your Volvo on Call app>

If your MQTT server is on the same device as the script omit the first line.
If your MQTT server is not secured with a username and a password the line looks as follows:
mqtt_url: mqtt://<IP Address>:1883

I hope this is sufficient to make it work

Regards
