### ISSUE TITLE
What is the call argument

### ISSUE THREAD

**Issue by tnemrap** [molobrakos/volvooncall#7]
Everything works fine but i can not fugure out what the call argument is used for?

**Comment by molobrakos** [comment]
Sorry for late response, yes @nikagl is correct, it is for issuing any custom API command not currently supported by the library.

**Comment by smikaelsson** [comment]
The official app supports blink and blink+honk but I didn't get that to work with any command I tried. Any of you know what those commands are?

**Comment by nikagl** [comment]
I have searched too but couldn't get it going either. I would have to use some proxy again (I used Charles Proxy in the past) to see what json calls are being performed in what order. As it's not the most important feature to be able to control (although it would be fun to have the car honk it's horn too when the alarm in the house goes off) I didn't yet try it...

**Comment by tnemrap** [comment]
Did you find the syntax for honk and blink?

**Comment by smikaelsson** [comment]
Hey,
Yes I did! I looked at what my watch app was sending and got it from there.
I’ll look it up when I get home.

lör 26 maj 2018 kl. 20:51 skrev tnemrap <notifications@github.com>:
