### ISSUE TITLE
New API for Volvo On Call

### ISSUE THREAD

**Issue by pezlin** [molobrakos/volvooncall#73]
Volvo has released a new API for VoC: https://developer.volvocars.com/

**Comment by nikagersonlohman** [comment]
This is not an API for VoC. It's an API to access Vehicle information and is pretty similar to VoC (I recognise a lot of items) but still much is missing... See also the message I posted about this a while ago:
https://github.com/molobrakos/volvooncall/issues/71

If anyone needs more info, contact me. I have more details and got a test account available.
