### ISSUE TITLE
Migrate away from hbmqtt

### ISSUE THREAD

**Issue by fabaff** [molobrakos/volvooncall#78]
`hbmqtt` is no longer [maintained](https://github.com/beerfactory/hbmqtt/issues/235).

Please migrate to [amqtt](https://github.com/Yakifo/amqtt).

Thanks

**Comment by cdce8p** [comment]
/CC: @decompil3d Maybe you could help?
According to the docs, the transition seems to be pretty strait forward. https://amqtt.readthedocs.io/en/latest/transition.html
This would probably also allow opening up the `websockets` dependency once again. It's currently pinned to `<=8.1` which can cause dependency conflicts in Home Assistant. At least some require `>10.0`.

**Comment by decompil3d** [comment]
I'll give it a go, but there is no test coverage for the MQTT portion of the module, so I cannot verify any changes here. So I'll post as a draft PR and perhaps one of y'all can checkout my branch and verify before we merge+publish?

**Comment by cdce8p** [comment]
I neither use the library nor the Home Assistant integration unfortunately.

You could consider doing a `pre-release` first. Although I don't know if that will get you any more feedback. Just from what I understand, `amqtt` should be a drop in replacement. It seems to be well maintained to. Maybe not ideal, but testing in "production" is also an option. At least as long as one can reasonable confident that the changes should work, which I would be in this case.

**Comment by cdce8p** [comment]
@decompil3d Thanks for picking this up btw!

**Comment by decompil3d** [comment]
The Home Assistant integration doesn't use MQTT at this point -- it consumes the outputs of `dashboard.py` so it's fairly low impact to release this. If it breaks folks can downgrade and then open an issue here.

**Comment by cdce8p** [comment]
> The Home Assistant integration doesn't use MQTT at this point -- it consumes the outputs of `dashboard.py` so it's fairly low impact to release this. If it breaks folks can downgrade and then open an issue here.

Sound like we should go for it then :)

**Comment by cdce8p** [comment]
Thanks @decompil3d! I've opened a PR for Home-Assistant to update the dependency.
https://github.com/home-assistant/core/pull/64942
