### ISSUE TITLE
Heater error with Home Assistant

### ISSUE THREAD

**Issue by tleegaard** [molobrakos/volvooncall#8]
I get this error with the latest version installed:
 ``
17-03-12 19:42:51 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 215, in async_update_ha_state
    state = self.state
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 326, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/volvooncall.py", line 30, in is_on
    return self.vehicle.is_heater_on
  File "/home/homeassistant/.homeassistant/deps/volvooncall.py", line 185, in is_heater_on
    self.heater['status'] != 'off')
KeyError: 'status'
``

I do have a heater in my Volvo, but reading current state is not supported.

**Comment by molobrakos** [comment]
Thanks for reporting. May I ask what `voc print` displays (especially the `heater` section)?
(for me I get the following:

```
  .. stuff
  "heater": {
    "status": "off", 
    "timestamp": "(time)", 
    "timer1": {
      "state": false, 
      "time": "(time)"
    }, 
    "seatSelection": {
      "frontPassengerSide": false, 
      "rearMid": false, 
      "frontDriverSide": false, 
      "rearPassengerSide": false, 
      "rearDriverSide": false
    }, 
    "timer2": {
      "state": false, 
      "time": "(time)"
    }
  }, 

```

**Comment by tleegaard** [comment]
My heater sections looks like this:
```
  "heater": {
    "timestamp": "2017-03-11T16:28:39+0000", 
    "timer2": {
      "state": false, 
      "time": "11:00"
    }, 
    "timer1": {
      "state": false, 
      "time": "07:25"
    }
  }, 
```

**Comment by molobrakos** [comment]
Ah, ok, interesting. 
Maybe this change solves it?
https://github.com/molobrakos/volvooncall/commit/5749ed6e3f765a80fe495e9e8e340225997e86d3

**Comment by angarok** [comment]
I too have this issue. Perhaps seeing the heater state is a feature that is only available on some models or modelyears? I have a 2013 V70. Anyway, the change in commit 5749ed6 seems to have fixed the issue for me and it also made the heater switch appear that was previously missing.

Big thanks for your work, it is greatly appreciated!

//Jonas

**Comment by molobrakos** [comment]
@angarok, thanks for feedback! @tleegaard, can you also please confirm? Then I'll update HA.

**Comment by tleegaard** [comment]
https://github.com/molobrakos/volvooncall/commit/5749ed6e3f765a80fe495e9e8e340225997e86d3 does indeed solve the error :-)

**Comment by molobrakos** [comment]
btw, shoud the heater switch rather not be enabled at all if the heater attribute is not present? (i.e. does the switch work if the attribute is missing?)

**Comment by angarok** [comment]
I haven't had time to test the heater switch yet, will do soon. But if it works I would like to keep it so I can add it to automations i HA.

**Comment by tleegaard** [comment]
Not even Volvos own app provides me with a status when activating the heater, so please keep the switch available in HA :-)
