### ISSUE TITLE
XC40 P8 2021 support

### ISSUE THREAD

**Issue by Veelu** [molobrakos/volvooncall#80]
Do you know if this library will work with XC40 P8 2021 model? When I tested the library I just get the message '401, Unauthorized'.

**Comment by Veelu** [comment]
Or is it so that only models on this list are supported?
https://www.volvocars.com/en-ca/support/manuals/xc60/2019w17/volvo-on-call/volvo-on-call-app/available-volvo-on-call-app-functions-per-vehicle-model

**Comment by decompil3d** [comment]
Newer models that use the Android Auto based infotainment do not seem to work with this package. See #84 for more details. I am about to sell my Volvo in the next several months, so I don't plan to dig into updating this module too much more. But PRs are welcome to add newer vehicle support.
