### ISSUE TITLE
Error Websockets

### ISSUE THREAD

**Issue by mazim-co** [molobrakos/volvooncall#83]
Hello there -  I'm not able to finish the setup because I'm getting following error:

`error: websockets 10.2 is installed but websockets<10.0,>=9.0 is required by {'amqtt'}`

Any ideas how I can fix this?

**Comment by decompil3d** [comment]
Version 0.10.0 moves the MQTT dependency to `extras_require` and also drops the explicit `websockets` dependency. So try installing the newer version.
